### ISSUE TITLE
Installation of drivers fails when there is no .espressif/dist directory on the computer

### ISSUE THREAD

**Issue by georgik** [espressif/idf-installer#86]
How to simulate: Clean computer with no .espressif/dist
Select installation of drivers.
The installer fails:
```
Running command: C:\Users\Lenovo\AppData\Local\Temp\is-81ISJ.tmp\idf-env.exe driver install  --ftdi --silabs --espressif
                          Downloading https://www.silabs.com/documents/public/software/CP210x_Universal_Windows_Driver.zip to C:\Users\Lenovo/.espressif/dist/cp210x.zi
                          thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 3, kind: NotFound, message: "The system cannot find the path specified." }', src\package.rs:146:6
                          note: run with `RUST_BACKTRACE=1` environment variable to display a backtrac
                          thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Any { .. }', src\package.rs:148:1
```

Workaround: create `~/.espressif/dist` directory or run the installer without drivers and second time with drivers.

**Comment by georgik** [comment]
Solved in https://github.com/espressif/idf-installer/releases/tag/online-2.12-beta-08
